name: Release

on:
  release:
    types: [published]

env:
    DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

permissions:
    contents: write
    packages: write

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:      
        - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - uses: actions/checkout@v4
        - name: Build & Publish
          shell: pwsh
          run: |
            dotnet restore
            dotnet build -c Release
            dotnet publish -c Release -o ./bin/publish
            Compress-Archive ./bin/publish/* ./bin/O365Logs2LA.zip
        - name: Add zip to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ./bin/O365Logs2LA.zip
            asset_name: O365Logs2LA-$tag.zip
            overwrite: true
    Docker:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Push to github docker registry
          run: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build -t ghcr.io/surestacks/o365logs2la:latest -t ghcr.io/surestacks/o365logs2la:${{ github.event.release.tag_name }} .
            docker push --all-tags ghcr.io/surestacks/o365logs2la:latest