name: Release

on:
  release:
    types: [published]

env:
    DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
    build:
        runs-on: ubuntu-latest
        steps:      
        - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - uses: actions/checkout@v4
        - name: Build
          run: |
            dotnet build -c Release
        - name: Publish
          run: |
            dotnet publish -c Release -o ./publish
        - name: Zip
          run: 
            cd publish
            version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            zip -r ../O365Logs2LA-$version.zip .
        - name: Upload
          uses: actions/upload-artifact@v4
          with:
            name: publish
            path: O365Logs2LA-*.zip