name: Release

on:
  release:
    types: [published]

env:
    DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

permissions:
    contents: write

jobs:
    Release:
        runs-on: ubuntu-latest
        steps:      
        - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - uses: actions/checkout@v4
        - name: Build & Publish
          shell: pwsh
          run: |
            dotnet restore
            dotnet build -c Release
            dotnet publish -c Release -o ./bin/publish
            Compress-Archive ./bin/publish/* ./bin/O365Logs2LA.zip
        - name: Add zip to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ./bin/O365Logs2LA.zip
            asset_name: O365Logs2LA-$tag.zip
            overwrite: true